version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: z9p+VIf4i3zHPz1EcNXxiA==
  DOCKER_PASS:
    secure: 7RwKlBUv2qxXMJYfQbAeH0moWB5EZRhqfiPeGPykDOxJD5U8ChgXPPlH0e9OLlKM
install:
  - ps: .\appveyor\install.ps1

build_script:
  - ps: .\appveyor\build.ps1

test_script:
  - ps: .\appveyor\test.ps1