version: 1.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: 2flXvzVdw16TSVRWNApT2mPPxP/RVwx3Nj8dJvqV9iNAvkf8cehBDbvYeykg2xtj
  DOCKER_PASS:
    secure: M8IUlFrsHzvLBkqcr/qzHRv42PiUf21D/ZSU/1uAXa/9R2VRSa2Zuz9oSyrkPFLy
install:
  - ps: .\install.ps1

build_script:
  - ps: .\build.ps1

test_script:
  - ps: .\test.ps1